name: blood_sos
description: Blood SOS App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.27.0
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.17.5
  firebase_messaging: ^14.9.4
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.6
  flutter_map: ^6.1.0
  flutter_map_cancellable_tile_provider: ^1.0.0
  image_cropper: ^5.0.1
  image_picker: ^1.1.2
  geolocator: ^10.1.1
  geocoding: ^3.0.0
  internet_connection_checker: ^1.0.0+1
  flutter_rating_bar: ^4.0.1
  dio: ^5.8.0+1
  infinite_scroll_pagination: ^4.1.0
  moment_dart: ^2.2.1   # <<< BU EKLENDÄ°

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

#dependency_overrides:
 # url_launcher_ios: 6.1.0
